add support for PCI device id bcce
OPAE/opae-libs pull request #181
Opened 2021-06-05 14:48 UTC by fpgamatt

Add support for the officially reservered PCI device id
for OFS devices.

Signed-off-by: Matthew Gerlach <matthew.gerlach@linux.intel.com>

2021-06-07 21:20 UTC, tswhison submitted a review, later dismissed

2021-06-07 21:51 UTC, r-rojo commented on plugins/xfpga/sysfs.c
> +
This code looks a lot like what is implemented in make_sysfs_object.
Seems to me this needs to be refactored so that we don't have duplicate code.

2021-06-07 21:52 UTC, r-rojo requested changes
refactor find_glob_path and make_sysfs_object to avoid duplicating code.

2021-06-08 18:00 UTC, r-rojo commented
Will these changes be backwards compatible with previous kernel versions and sysfs paths? Is there a unit test for the new function (find_glob_paths)?

2021-06-08 18:40 UTC, r-rojo approved these changes

2021-06-08 20:20 UTC, merged